# .github/workflows/chromatic.yml

# Workflow name
name: ðŸ“– Storybook (via Chromatic)

# Event for the workflow
on:
  # ðŸ‘‡ Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
  # ðŸ‘‡ Triggers the workflow on pull request events to the main branch
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'packages/ui-tests/cypress/**'
    types: [opened, synchronize, reopened, ready_for_review]

# List of jobs
jobs:
  chromatic-deployment:
    if: github.repository == 'KaotoIO/kaoto' && github.actor != 'renovate[bot]' && !github.event.pull_request.draft
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          # ðŸ‘‡ Fetches all Git history so that Chromatic can compare against the previous version
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
          cache: 'yarn'

      # ðŸ‘‡ Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
      - name: Install dependencies
        run: yarn

      # ðŸ‘‡ Builds the kaoto/ui in library mode
      - name: Build ui library
        run: yarn workspace @kaoto/kaoto run build:lib

      # ðŸ‘‡ Remove ui-mockups directory from stories
      - name: Remove ui-mockups directory
        run: rm -rf packages/ui-tests/stories/ui-mockups

      # ðŸ‘‡ Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v13.3.5
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        # Chromatic GitHub Action options
        with:
          #ðŸ‘‡ Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          buildScriptName: build:storybook
          workingDir: packages/ui-tests
