# .github/workflows/chromatic.yml

# Workflow name
name: ðŸ“– Storybook (via Chromatic)

# Event for the workflow
on:
  # ðŸ‘‡ Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
  # ðŸ‘‡ Triggers the workflow on pull request events to the main branch
  pull_request:
    branches:
      - main

# List of jobs
jobs:
  chromatic-deployment:
    if: github.repository == 'KaotoIO/kaoto-next' && github.actor != 'renovate[bot]'
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          # ðŸ‘‡ Fetches all Git history so that Chromatic can compare against the previous version
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto-next'
          cache: 'yarn'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # ðŸ‘‡ Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
      - name: Install dependencies
        run: yarn

      # ðŸ‘‡ Builds the kaoto-next/ui in library mode
      - name: Build ui library
        run: yarn workspace @kaoto-next/ui run build:lib

      # ðŸ‘‡ Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          #ðŸ‘‡ Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: chpt_7a4940aa65b14ab
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: build:storybook
          workingDir: packages/ui-tests
