name: ğŸš€ Build and Deploy main
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "deploy-main"
  cancel-in-progress: true

jobs:
  build-distribution:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ›°ï¸ Checkout source code"
        uses: actions/checkout@v4

      - name: "ğŸ›°ï¸ Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@kaoto-next"
          cache: "yarn"

      - name: "ğŸ›°ï¸ Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: "ğŸ”§ Install dependencies"
        run: yarn

      # Build packages excluding @kaoto-next/camel-catalog since it was build during installing dependencies
      - name: "ğŸ”§ Build packages"
        run: |
          yarn workspaces foreach --verbose --topological-dev --exclude @kaoto-next/camel-catalog run build

      - name: "ğŸ”§ Tar UI Dist"
        shell: bash
        run: |
          tar -czf ${{ runner.temp }}/kaoto-ui.tgz -C packages/ui/dist .
          ls -lh ${{ runner.temp }}/kaoto-ui.tgz

      - name: "ğŸ”§ Persist UI Dist"
        uses: actions/upload-artifact@v3
        with:
          name: "kaoto-ui-${{ github.run_id }}"
          path: "${{ runner.temp }}/kaoto-ui.tgz"
          retention-days: 1

  deploy-pages:
    runs-on: ubuntu-latest
    needs:
      - build-distribution
    steps:
      - name: "ğŸ›°ï¸ Checkout source code"
        uses: actions/checkout@v4

      - name: "ğŸ›°ï¸ Setup Pages"
        uses: actions/configure-pages@v4

      - name: "ğŸ›°ï¸ Download UI Dist"
        uses: actions/download-artifact@v4
        with:
          name: kaoto-ui-${{ github.run_id }}
          path: "${{ runner.temp }}"

      - name: "ğŸ›°ï¸ Extract UI Dist"
        shell: bash
        run: |
          mkdir -p packages/ui/dist
          tar -xzf "${{ runner.temp }}/kaoto-ui.tgz" -C packages/ui/dist

      - name: "ğŸ“¤ Upload artifact @kaoto-next/ui web application"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "packages/ui/dist"

      - name: "ğŸš€ Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-images:
    runs-on: ubuntu-latest
    needs:
      - build-distribution
    steps:
      - name: "ğŸ›°ï¸ Checkout source code"
        uses: actions/checkout@v4

      - name: "ğŸ›°ï¸ Download UI Dist"
        uses: actions/download-artifact@v4
        with:
          name: kaoto-ui-${{ github.run_id }}
          path: "${{ runner.temp }}"

      - name: "ğŸ›°ï¸ Extract UI Dist"
        shell: bash
        run: |
          mkdir -p packages/ui/dist
          tar -xzf "${{ runner.temp }}/kaoto-ui.tgz" -C packages/ui/dist

      - name: "ğŸ›°ï¸ Login to Container Registry"
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: "ğŸ”§ Build Container Image"
        shell: bash
        # TODO: the container image name should be configurable via vars/secrets
        run: |
          docker build -t "quay.io/kaotoio/kaoto-app:main" .

      - name: "ğŸ“¤ Upload Container Image"
        shell: bash
        run: |
          docker push quay.io/kaotoio/kaoto-app:main
